server.port: 8083
spring:
  application:
    name: service3
  sleuth:
    baggage-keys:
      - baggage
      - key
    log.slf4j.whitelisted-mdc-keys:
      - key

logging.level.org.springframework.cloud.sleuth: DEBUG

management.endpoints.web.base-path: /
management.endpoints.web.exposure.include: "*"

logging.pattern.level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-},%X{key:-}]"