server.port: 8082
spring:
  application:
    name: service2
  sleuth:
    propagation:
      type:
        - b3
        - w3c
    baggage:
      remote-fields:
        - baggage
        - key
      correlation-fields:
        - key
    sampler:
      probability: 1.0

logging.level.org.springframework.cloud.sleuth: DEBUG

management.endpoints.web.base-path: /
management.endpoints.web.exposure.include: "*"

logging.pattern.level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-},%X{key:-}]"

wavefront.application.name: sleuth-documentation-apps
wavefront.application.service: service2
