server.port: 8082
spring:
  application:
    name: service2
  sleuth:
    baggage:
      remote-keys:
        - baggage
        - key
      correlation-keys:
        - key

logging.level.org.springframework.cloud.sleuth: DEBUG

management.endpoints.web.base-path: /
management.endpoints.web.exposure.include: "*"

logging.pattern.level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-},%X{key:-}]"
