server.port: 8081
spring:
  application:
    name: service1
  sleuth:
    baggage:
      remote-fields:
        - baggage
        - key
      correlation-fields:
        - key


logging.level.org.springframework.cloud.sleuth: DEBUG

management.endpoints.web.base-path: /
management.endpoints.web.exposure.include: "*"

logging.pattern.level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-},%X{key:-}]"
