server.port: 8084
spring:
  application:
    name: service4
  sleuth:
    baggage:
      remote-fields:
        - baggage
        - key
      correlation-fields:
        - key

logging.level.org.springframework.cloud.sleuth: DEBUG

management.endpoints.web.base-path: /
management.endpoints.web.exposure.include: "*"
