server.port: 8084
spring:
  application:
    name: service4
  sleuth:
    baggage:
      remote-fields:
        - baggage
        - key
      correlation-fields:
        - key
    otel:
      config:
        trace-id-ratio-based: 1.0

logging.level.org.springframework.cloud.sleuth: DEBUG

management.endpoints.web.base-path: /
management.endpoints.web.exposure.include: "*"

logging.pattern.level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-},%X{key:-}]"
